### ISSUE TITLE
Data does not stores in backup!

### ISSUE THREAD

**Issue by Coolified** [Scientific-Guy/enhanced.db#2]
So well i was using backup as true for enhanced,db but it never stored!

I couldn't join **Discord Server** but i created GitHub Account and i want the answer because it is needed for my website so please help me a bit faster please...

**Comment by scientific-dev** [comment]
First wait what version you are using and did setup the backup as `true`?

**Comment by Coolified** [comment]
Yes i set it to `true` and i am using 0.1.9 and my second project 0.1.5

**Comment by scientific-dev** [comment]
Uhmmm.
Backup option type is not a boolean its a string eg `/backup/mybackup.sqlite` something like this

`db.options({backup: '/backup/mybackup.sqlite/'})`

So that will be the directory you will be storing your backup....
And upgrade to 0.1.9 in ur second project and make sure that you keep seperate sqlite files for each table and default database table to prevent crash....

**Comment by Coolified** [comment]
Well, let me try

**Comment by scientific-dev** [comment]
https://enhanceddb.science.repl.co/#options

To view all typeof and description of options

**Comment by Coolified** [comment]
OH, thanks now it works and secondly how to import the data to the main file

**Comment by scientific-dev** [comment]
https://enhanceddb.science.repl.co/#import

Use import() and use read for extracting it from backup file
https://enhanceddb.science.repl.co/#read

**Comment by Coolified** [comment]
Is there any better methods instead of reading and import

**Comment by scientific-dev** [comment]
Might be in future updates....

**Comment by Coolified** [comment]
Oh thanks
